using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#pragma warning disable RSEXPERIMENTAL002

namespace Generator;

[Generator(LanguageNames.CSharp)]
public class WhenInterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all .Debug() calls on ILogger
        var callSites = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is InvocationExpressionSyntax inv &&
                inv.Expression is MemberAccessExpressionSyntax member &&
                member.Name.Identifier.Text == "Debug" &&
                inv.ArgumentList.Arguments.Count == 1 &&
                inv.ArgumentList.Arguments[0].Expression is InterpolatedStringExpressionSyntax,
            transform: static (ctx, ct) =>
            {
                var inv = (InvocationExpressionSyntax)ctx.Node;
                var location = ctx.SemanticModel.GetInterceptableLocation(inv, ct);
                if (location is null) return null;

                // Get the full expression text for display
                var exprText = inv.Expression.ToString();
                return new CallSiteInfo(location, exprText);
            })
            .Where(static x => x is not null);

        var collected = callSites.Collect();
        context.RegisterImplementationSourceOutput(collected, static (spc, sites) =>
        {
            if (sites.IsDefaultOrEmpty) return;
            EmitInterceptors(spc, sites!);
        });
    }

    private static void EmitInterceptors(SourceProductionContext spc, ImmutableArray<CallSiteInfo?> sites)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    sealed file class InterceptsLocationAttribute : Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("namespace WhenTest");
        sb.AppendLine("{");
        sb.AppendLine("    file static class GeneratedInterceptors");
        sb.AppendLine("    {");

        int index = 0;
        foreach (var site in sites)
        {
            if (site is null) continue;
            var loc = site.Location;

            sb.AppendLine("        // Intercepting: " + site.ExpressionText);
            sb.AppendLine("        [global::System.Runtime.CompilerServices.InterceptsLocation("
                + loc.Version + ", \"" + loc.Data + "\")]");
            sb.AppendLine("        internal static void __Debug_" + index
                + "(this global::WhenTest.ILogger logger, ref global::WhenTest.LogDebugHandler handler)");
            sb.AppendLine("        {");
            sb.AppendLine("            Console.WriteLine(\"  [INTERCEPTOR] receiver type = \" + logger.GetType().Name);");
            sb.AppendLine("            Console.WriteLine(\"  [INTERCEPTOR] handler.IsEnabled = \" + handler.IsEnabled);");
            sb.AppendLine("            if (!handler.IsEnabled)");
            sb.AppendLine("            {");
            sb.AppendLine("                Console.WriteLine(\"  [INTERCEPTOR] => skipped (disabled)\");");
            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine("            var text = System.Text.Encoding.UTF8.GetString(handler.GetTextWritten());");
            sb.AppendLine("            Console.WriteLine(\"  [INTERCEPTOR] => dispatching: \" + text);");
            sb.AppendLine("        }");
            sb.AppendLine();
            index++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("WhenInterceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal class CallSiteInfo
{
    public InterceptableLocation Location { get; }
    public string ExpressionText { get; }
    public CallSiteInfo(InterceptableLocation location, string exprText)
    {
        Location = location;
        ExpressionText = exprText;
    }
}

#pragma warning restore RSEXPERIMENTAL002
