using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Logsmith.Generator.Interception;

/// <summary>
/// Emits interceptor methods and the InterceptsLocationAttribute definition.
/// </summary>
internal static class InterceptorEmitter
{
    private static readonly string[] LogLevelNames =
    {
        "Trace", "Debug", "Information", "Warning", "Error", "Critical"
    };

    private static readonly string[] HandlerTypeNames =
    {
        "LogTraceHandler", "LogDebugHandler", "LogInformationHandler",
        "LogWarningHandler", "LogErrorHandler", "LogCriticalHandler"
    };

    /// <summary>
    /// Emits the complete interceptor source file for all chains.
    /// </summary>
    internal static string Emit(IReadOnlyList<InterceptorChain> chains)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Emit InterceptsLocationAttribute
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    sealed file class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Collect unique carrier shapes
        var carrierShapes = new Dictionary<string, InterceptorChain>();
        foreach (var chain in chains)
        {
            if (chain.CarrierShapeId != null && !carrierShapes.ContainsKey(chain.CarrierShapeId))
                carrierShapes[chain.CarrierShapeId] = chain;
        }

        sb.AppendLine("namespace Logsmith.Generated");
        sb.AppendLine("{");

        // Emit carrier types (non-file-scoped, internal, so interceptors can reference them)
        foreach (var kvp in carrierShapes)
        {
            sb.Append(CarrierEmitter.EmitCarrier(kvp.Key, kvp.Value));
            sb.AppendLine();
        }

        // Emit interceptor methods
        sb.AppendLine("    file static class LogInterceptors");
        sb.AppendLine("    {");

        int index = 0;
        foreach (var chain in chains)
        {
            foreach (var step in chain.Steps)
            {
                sb.Append(EmitInterceptorMethod(step, chain, index));
                sb.AppendLine();
                index++;
            }
        }

        // Emit static counter fields for sampling/rate-limiting
        int counterIndex = 0;
        foreach (var chain in chains)
        {
            foreach (var step in chain.Steps)
            {
                if (step.MethodName == "Sampled")
                {
                    sb.AppendLine($"        private static int __sampleCounter_{counterIndex};");
                }
                else if (step.MethodName == "RateLimited")
                {
                    sb.AppendLine($"        private static long __rateWindow_{counterIndex};");
                    sb.AppendLine($"        private static int __rateCount_{counterIndex};");
                }
                counterIndex++;
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EmitInterceptorMethod(
        InterceptorCallSite site,
        InterceptorChain chain,
        int index)
    {
        switch (site.Kind)
        {
            case InterceptorCallKind.DirectTerminal:
                return EmitDirectTerminalInterceptor(site, index);
            case InterceptorCallKind.ChainStart:
                return EmitChainStartInterceptor(site, chain, index);
            case InterceptorCallKind.ChainIntermediate:
                return EmitChainIntermediateInterceptor(site, chain, index);
            case InterceptorCallKind.ChainTerminal:
                return EmitChainTerminalInterceptor(site, chain, index);
            default:
                return "";
        }
    }

    /// <summary>
    /// Emits an interceptor for a direct terminal call like logger.Debug($"...").
    /// Adds caller info, event ID, and dispatches through the context.
    /// </summary>
    private static string EmitDirectTerminalInterceptor(InterceptorCallSite site, int index)
    {
        var sb = new StringBuilder();
        string levelName = LogLevelNames[site.LogLevel];

        sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({site.Location.Version}, \"{site.Location.Data}\")]");

        if (site.HasHandlerParam)
        {
            string handlerType = HandlerTypeNames[site.LogLevel];
            if (site.HasExceptionParam)
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, global::System.Exception? exception, ref global::Logsmith.Handlers.{handlerType} handler)");
            }
            else
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, ref global::Logsmith.Handlers.{handlerType} handler)");
            }
            sb.AppendLine("        {");
            sb.AppendLine("            if (!handler.IsEnabled) return;");
            sb.AppendLine("            var __info = new global::Logsmith.DispatchInfo");
            sb.AppendLine("            {");
            sb.AppendLine($"                Level = global::Logsmith.LogLevel.{levelName},");
            sb.AppendLine($"                EventId = {site.EventId},");
            sb.AppendLine("                Utf8Message = handler.GetTextWritten(),");
            sb.AppendLine("                Utf8Json = handler.GetJsonWritten(),");
            sb.AppendLine("                Exception = handler.Exception,");
            sb.AppendLine($"                CallerFile = @\"{EscapeVerbatimString(site.CallerFilePath)}\",");
            sb.AppendLine($"                CallerLine = {site.CallerLine},");
            sb.AppendLine($"                CallerMember = \"{EscapeString(site.CallerMember)}\",");
            sb.AppendLine("            };");
            sb.AppendLine("            @this.Context.Dispatch(in __info);");
            sb.AppendLine("        }");
        }
        else
        {
            // String-based overload
            if (site.HasExceptionParam)
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, string message, global::System.Exception? exception)");
            }
            else
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, string message)");
            }
            sb.AppendLine("        {");
            sb.AppendLine($"            if (!@this.IsEnabled(global::Logsmith.LogLevel.{levelName})) return;");
            sb.AppendLine("            var __bytes = global::System.Text.Encoding.UTF8.GetBytes(message);");
            sb.AppendLine("            var __info = new global::Logsmith.DispatchInfo");
            sb.AppendLine("            {");
            sb.AppendLine($"                Level = global::Logsmith.LogLevel.{levelName},");
            sb.AppendLine("                Utf8Message = __bytes,");
            sb.AppendLine($"                Exception = {(site.HasExceptionParam ? "exception" : "null")},");
            sb.AppendLine($"                CallerFile = @\"{EscapeVerbatimString(site.CallerFilePath)}\",");
            sb.AppendLine($"                CallerLine = {site.CallerLine},");
            sb.AppendLine($"                CallerMember = \"{EscapeString(site.CallerMember)}\",");
            sb.AppendLine("            };");
            sb.AppendLine("            @this.Context.Dispatch(in __info);");
            sb.AppendLine("        }");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits an interceptor for the start of a chain (When, Sampled, etc.).
    /// Creates a carrier or returns NullLogger.
    /// </summary>
    private static string EmitChainStartInterceptor(
        InterceptorCallSite site,
        InterceptorChain chain,
        int index)
    {
        var sb = new StringBuilder();
        string levelName = LogLevelNames[chain.TerminalLogLevel];
        string carrierType = $"LogCarrier_{chain.CarrierShapeId}";

        sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({site.Location.Version}, \"{site.Location.Data}\")]");

        switch (site.MethodName)
        {
            case "When":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __When_{index}(this global::Logsmith.ILogger @this, bool condition)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!condition || !@this.Context.IsEnabled(global::Logsmith.LogLevel.{levelName}))");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine($"            return {carrierType}.Rent(@this.Context);");
                sb.AppendLine("        }");
                break;

            case "Sampled":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __Sampled_{index}(this global::Logsmith.ILogger @this, int rate)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!@this.Context.IsEnabled(global::Logsmith.LogLevel.{levelName}))");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine($"            if ((global::System.Threading.Interlocked.Increment(ref __sampleCounter_{index}) % rate) != 0)");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine($"            return {carrierType}.Rent(@this.Context);");
                sb.AppendLine("        }");
                break;

            case "RateLimited":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __RateLimited_{index}(this global::Logsmith.ILogger @this, int maxPerSecond)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!@this.Context.IsEnabled(global::Logsmith.LogLevel.{levelName}))");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine($"            long __now = global::System.DateTime.UtcNow.Ticks / global::System.TimeSpan.TicksPerSecond;");
                sb.AppendLine($"            long __window = global::System.Threading.Volatile.Read(ref __rateWindow_{index});");
                sb.AppendLine("            if (__now != __window)");
                sb.AppendLine("            {");
                sb.AppendLine($"                global::System.Threading.Interlocked.Exchange(ref __rateWindow_{index}, __now);");
                sb.AppendLine($"                global::System.Threading.Interlocked.Exchange(ref __rateCount_{index}, 0);");
                sb.AppendLine("            }");
                sb.AppendLine($"            if (global::System.Threading.Interlocked.Increment(ref __rateCount_{index}) > maxPerSecond)");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine($"            return {carrierType}.Rent(@this.Context);");
                sb.AppendLine("        }");
                break;

            case "Tagged":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __Tagged_{index}(this global::Logsmith.ILogger @this, string tag)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!@this.Context.IsEnabled(global::Logsmith.LogLevel.{levelName}))");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine($"            var __carrier = {carrierType}.Rent(@this.Context);");
                sb.AppendLine("            __carrier.__tag = tag;");
                sb.AppendLine("            return __carrier;");
                sb.AppendLine("        }");
                break;
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits an interceptor for an intermediate chain step.
    /// Stores values on the carrier and returns it.
    /// </summary>
    private static string EmitChainIntermediateInterceptor(
        InterceptorCallSite site,
        InterceptorChain chain,
        int index)
    {
        var sb = new StringBuilder();
        string carrierType = $"LogCarrier_{chain.CarrierShapeId}";

        sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({site.Location.Version}, \"{site.Location.Data}\")]");

        switch (site.MethodName)
        {
            case "Tagged":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __Tagged_{index}(this global::Logsmith.ILogger @this, string tag)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (@this is {carrierType} __c) __c.__tag = tag;");
                sb.AppendLine("            return @this;");
                sb.AppendLine("        }");
                break;

            case "Sampled":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __Sampled_{index}(this global::Logsmith.ILogger @this, int rate)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if ((global::System.Threading.Interlocked.Increment(ref __sampleCounter_{index}) % rate) != 0)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (@this is {carrierType} __cr) __cr.Return();");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine("            }");
                sb.AppendLine("            return @this;");
                sb.AppendLine("        }");
                break;

            case "RateLimited":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __RateLimited_{index}(this global::Logsmith.ILogger @this, int maxPerSecond)");
                sb.AppendLine("        {");
                sb.AppendLine($"            long __now = global::System.DateTime.UtcNow.Ticks / global::System.TimeSpan.TicksPerSecond;");
                sb.AppendLine($"            long __window = global::System.Threading.Volatile.Read(ref __rateWindow_{index});");
                sb.AppendLine("            if (__now != __window)");
                sb.AppendLine("            {");
                sb.AppendLine($"                global::System.Threading.Interlocked.Exchange(ref __rateWindow_{index}, __now);");
                sb.AppendLine($"                global::System.Threading.Interlocked.Exchange(ref __rateCount_{index}, 0);");
                sb.AppendLine("            }");
                sb.AppendLine($"            if (global::System.Threading.Interlocked.Increment(ref __rateCount_{index}) > maxPerSecond)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (@this is {carrierType} __cr) __cr.Return();");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine("            }");
                sb.AppendLine("            return @this;");
                sb.AppendLine("        }");
                break;

            case "When":
                sb.AppendLine($"        internal static global::Logsmith.ILogger __When_{index}(this global::Logsmith.ILogger @this, bool condition)");
                sb.AppendLine("        {");
                sb.AppendLine("            if (!condition)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (@this is {carrierType} __cr) __cr.Return();");
                sb.AppendLine("                return global::Logsmith.NullLogger.Instance;");
                sb.AppendLine("            }");
                sb.AppendLine("            return @this;");
                sb.AppendLine("        }");
                break;
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits an interceptor for the terminal of a chain (Debug, etc.).
    /// Extracts accumulated state from the carrier, dispatches, and returns the carrier to the pool.
    /// </summary>
    private static string EmitChainTerminalInterceptor(
        InterceptorCallSite site,
        InterceptorChain chain,
        int index)
    {
        var sb = new StringBuilder();
        string levelName = LogLevelNames[site.LogLevel];
        string carrierType = $"LogCarrier_{chain.CarrierShapeId}";

        // Determine what fields the carrier has
        bool carrierHasTag = HasChainMethod(chain, "Tagged");

        sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({site.Location.Version}, \"{site.Location.Data}\")]");

        if (site.HasHandlerParam)
        {
            string handlerType = HandlerTypeNames[site.LogLevel];
            if (site.HasExceptionParam)
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, global::System.Exception? exception, ref global::Logsmith.Handlers.{handlerType} handler)");
            }
            else
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, ref global::Logsmith.Handlers.{handlerType} handler)");
            }
            sb.AppendLine("        {");
            sb.AppendLine("            if (!handler.IsEnabled) return;");

            // Extract carrier state
            sb.AppendLine($"            string? __tag = null;");
            sb.AppendLine($"            if (@this is {carrierType} __carrier)");
            sb.AppendLine("            {");
            if (carrierHasTag)
                sb.AppendLine("                __tag = __carrier.__tag;");
            sb.AppendLine("                __carrier.Return();");
            sb.AppendLine("            }");

            sb.AppendLine("            var __info = new global::Logsmith.DispatchInfo");
            sb.AppendLine("            {");
            sb.AppendLine($"                Level = global::Logsmith.LogLevel.{levelName},");
            sb.AppendLine($"                EventId = {site.EventId},");
            sb.AppendLine("                Utf8Message = handler.GetTextWritten(),");
            sb.AppendLine("                Utf8Json = handler.GetJsonWritten(),");
            sb.AppendLine("                Exception = handler.Exception,");
            sb.AppendLine("                Tag = __tag,");
            sb.AppendLine($"                CallerFile = @\"{EscapeVerbatimString(site.CallerFilePath)}\",");
            sb.AppendLine($"                CallerLine = {site.CallerLine},");
            sb.AppendLine($"                CallerMember = \"{EscapeString(site.CallerMember)}\",");
            sb.AppendLine("            };");
            sb.AppendLine("            @this.Context.Dispatch(in __info);");
            sb.AppendLine("        }");
        }
        else
        {
            // String-based terminal in a chain
            if (site.HasExceptionParam)
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, string message, global::System.Exception? exception)");
            }
            else
            {
                sb.AppendLine($"        internal static void __{levelName}_{index}(this global::Logsmith.ILogger @this, string message)");
            }
            sb.AppendLine("        {");
            sb.AppendLine($"            if (!@this.IsEnabled(global::Logsmith.LogLevel.{levelName})) return;");

            // Extract carrier state
            sb.AppendLine($"            string? __tag = null;");
            sb.AppendLine($"            if (@this is {carrierType} __carrier)");
            sb.AppendLine("            {");
            if (carrierHasTag)
                sb.AppendLine("                __tag = __carrier.__tag;");
            sb.AppendLine("                __carrier.Return();");
            sb.AppendLine("            }");

            sb.AppendLine("            var __bytes = global::System.Text.Encoding.UTF8.GetBytes(message);");
            sb.AppendLine("            var __info = new global::Logsmith.DispatchInfo");
            sb.AppendLine("            {");
            sb.AppendLine($"                Level = global::Logsmith.LogLevel.{levelName},");
            sb.AppendLine("                Utf8Message = __bytes,");
            sb.AppendLine($"                Exception = {(site.HasExceptionParam ? "exception" : "null")},");
            sb.AppendLine("                Tag = __tag,");
            sb.AppendLine($"                CallerFile = @\"{EscapeVerbatimString(site.CallerFilePath)}\",");
            sb.AppendLine($"                CallerLine = {site.CallerLine},");
            sb.AppendLine($"                CallerMember = \"{EscapeString(site.CallerMember)}\",");
            sb.AppendLine("            };");
            sb.AppendLine("            @this.Context.Dispatch(in __info);");
            sb.AppendLine("        }");
        }

        return sb.ToString();
    }

    private static bool HasChainMethod(InterceptorChain chain, string methodName)
    {
        return chain.Steps.Any(s => s.MethodName == methodName);
    }

    private static string EscapeString(string text)
    {
        return text
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r");
    }

    private static string EscapeVerbatimString(string text)
    {
        // In verbatim strings, only " needs escaping (doubled)
        return text.Replace("\"", "\"\"");
    }
}
