using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

#pragma warning disable RSEXPERIMENTAL002

namespace Generator;

[Generator(LanguageNames.CSharp)]
public class ConditionalInterceptorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var callSites = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is InvocationExpressionSyntax inv &&
                inv.Expression is MemberAccessExpressionSyntax member &&
                (member.Name.Identifier.Text == "TraceLog" ||
                 member.Name.Identifier.Text == "DebugLog"),
            transform: static (ctx, ct) => TransformCallSite(ctx, ct))
            .Where(static x => x is not null);

        var collected = callSites.Collect();

        context.RegisterImplementationSourceOutput(collected, static (spc, sites) =>
        {
            if (sites.IsDefaultOrEmpty) return;
            EmitInterceptors(spc, sites!);
        });
    }

    private static CallSiteInfo? TransformCallSite(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        var inv = (InvocationExpressionSyntax)ctx.Node;
        var member = (MemberAccessExpressionSyntax)inv.Expression;
        var methodName = member.Name.Identifier.Text;

        var location = ctx.SemanticModel.GetInterceptableLocation(inv, ct);
        if (location is null) return null;

        return new CallSiteInfo(methodName, location);
    }

    private static void EmitInterceptors(SourceProductionContext spc, ImmutableArray<CallSiteInfo?> sites)
    {
        var sb = new StringBuilder();
        sb.AppendLine("""
            // <auto-generated/>
            using System;
            using System.Diagnostics;

            namespace System.Runtime.CompilerServices
            {
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                sealed file class InterceptsLocationAttribute : Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        _ = version;
                        _ = data;
                    }
                }
            }

            namespace InterceptorTest
            {
                file static class GeneratedInterceptors
                {
            """);

        int index = 0;
        foreach (var site in sites)
        {
            if (site is null) continue;

            var conditionalSymbol = site.MethodName == "TraceLog" ? "TRACE" : "DEBUG";
            var loc = site.Location;

            sb.AppendLine("        [Conditional(\"" + conditionalSymbol + "\")]");
            sb.AppendLine("        [global::System.Runtime.CompilerServices.InterceptsLocation(" + loc.Version + ", \"" + loc.Data + "\")]");
            sb.AppendLine("        internal static void __" + site.MethodName + "_" + index + "(this TestLogger logger, string message)");
            sb.AppendLine("        {");
            sb.AppendLine("            Console.WriteLine(\"  [INTERCEPTOR] " + site.MethodName + " called: \" + message);");
            sb.AppendLine("        }");
            index++;
        }

        sb.AppendLine("""
                }
            }
            """);

        spc.AddSource("Interceptors.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}

internal class CallSiteInfo
{
    public string MethodName { get; }
    public InterceptableLocation Location { get; }
    public CallSiteInfo(string methodName, InterceptableLocation location)
    {
        MethodName = methodName;
        Location = location;
    }
}

#pragma warning restore RSEXPERIMENTAL002
