using System.Collections.Generic;
using System.Linq;
using System.Text;
using Logsmith.Generator.Models;

namespace Logsmith.Generator.Emission;

internal static class MethodEmitter
{
    private static readonly string[] LogLevelNames =
    {
        "Trace", "Debug", "Information", "Warning", "Error", "Critical", "None"
    };

    internal static string EmitClassFile(
        string namespaceName,
        IReadOnlyList<ContainingTypeInfo> typeChain,
        IReadOnlyList<LogMethodInfo> methods)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        // Emit inner content at zero indent, then re-indent for nesting depth
        var innerSb = new StringBuilder();

        // Emit CategoryName constant
        var category = methods[0].Category;
        innerSb.AppendLine($"    public const string CategoryName = \"{EscapeString(category)}\";");

        // Emit static LoggerContext field for standard/shared mode
        if (methods[0].Mode != GeneratorMode.Abstraction)
        {
            innerSb.AppendLine($"    private static global::Logsmith.LoggerContext? __loggerContext;");
        }

        for (int i = 0; i < methods.Count; i++)
        {
            if (i > 0) innerSb.AppendLine();
            innerSb.Append(EmitMethodBody(methods[i]));
        }

        // Emit static counter fields for sampling/rate-limiting
        foreach (var method in methods)
        {
            var counterFields = EmitStaticCounterFields(method);
            if (!string.IsNullOrEmpty(counterFields))
            {
                innerSb.AppendLine();
                innerSb.Append(counterFields);
            }
        }

        // Calculate base indent for innermost class content
        // Outer classes add indent; the innermost class body content gets (chainLength - 1) * 4 extra spaces
        int extraIndent = (typeChain.Count - 1) * 4;
        string extraIndentStr = extraIndent > 0 ? new string(' ', extraIndent) : "";

        // Open nesting wrappers (outermost first)
        for (int i = 0; i < typeChain.Count; i++)
        {
            string indent = i > 0 ? new string(' ', i * 4) : "";
            sb.AppendLine($"{indent}{typeChain[i].Modifiers}partial {typeChain[i].Keyword} {typeChain[i].Name}");
            sb.AppendLine($"{indent}{{");
        }

        // Re-indent inner content
        string innerContent = innerSb.ToString();
        if (extraIndent > 0)
        {
            var lines = innerContent.Split('\n');
            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i];
                // Preserve empty lines as-is (may have trailing \r)
                string trimmed = line.TrimEnd('\r');
                if (trimmed.Length == 0)
                    sb.AppendLine();
                else
                    sb.AppendLine(extraIndentStr + trimmed);
            }
        }
        else
        {
            sb.Append(innerContent);
        }

        // Close nesting wrappers (innermost first)
        for (int i = typeChain.Count - 1; i >= 0; i--)
        {
            string indent = i > 0 ? new string(' ', i * 4) : "";
            sb.AppendLine($"{indent}}}");
        }

        return sb.ToString();
    }

    internal static string EmitMethodBody(LogMethodInfo method)
    {
        if (method.Mode == GeneratorMode.Abstraction)
            return EmitAbstractionMethodBody(method);

        return EmitStandardMethodBody(method);
    }

    private static string EmitStandardMethodBody(LogMethodInfo method)
    {
        var sb = new StringBuilder();
        string levelName = method.Level >= 0 && method.Level < LogLevelNames.Length
            ? LogLevelNames[method.Level]
            : "Information";

        // Conditional attribute
        int threshold = ConditionalCompilation.ParseThreshold(method.ConditionalLevel);
        bool applyConditional = ConditionalCompilation.ShouldApplyConditional(
            method.Level, threshold, method.AlwaysEmit);

        if (applyConditional)
        {
            sb.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
        }

        // Method signature
        sb.Append($"    {method.AccessModifier}static partial void {method.MethodName}(");
        sb.Append(string.Join(", ", method.Parameters.Select(p => FormatParameter(p))));
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // IsEnabled early-exit guard
        if (method.HasExplicitSink)
        {
            var sinkParam = method.Parameters.First(p => p.Kind == ParameterKind.Sink);
            sb.AppendLine($"        if (!{sinkParam.Name}.IsEnabled(global::Logsmith.LogLevel.{levelName}))");
            sb.AppendLine("            return;");
        }
        else
        {
            // LoggerContext lazy initialization and IsEnabled check
            sb.AppendLine($"        var __ctx = __loggerContext ??= global::Logsmith.LogManager.GetLogger(\"{EscapeString(method.Category)}\").Context;");
            sb.AppendLine($"        if (!__ctx.IsEnabled(global::Logsmith.LogLevel.{levelName}))");
            sb.AppendLine("            return;");
        }

        // Sampling guard
        if (method.SampleRate > 1)
        {
            sb.AppendLine();
            sb.Append(EmitSamplingGuard(method));
        }

        // Rate-limiting guard
        if (method.MaxPerSecond > 0)
        {
            sb.AppendLine();
            sb.Append(EmitRateLimitGuard(method));
        }

        sb.AppendLine();

        // Text path
        int bufferSize = EstimateBufferSize(method);
        sb.AppendLine($"        global::System.Span<byte> __buffer = stackalloc byte[{bufferSize}];");
        sb.AppendLine("        var writer = new global::Logsmith.Utf8LogWriter(__buffer);");
        sb.Append(TextPathEmitter.Emit(method));
        sb.AppendLine("        var __utf8Message = writer.GetWritten();");
        sb.AppendLine();

        // JSON path (inline) — only if there are message parameters
        var messageParams = method.Parameters.Where(p => p.Kind == ParameterKind.MessageParam).ToList();
        bool hasJsonPath = messageParams.Count > 0;
        if (hasJsonPath)
        {
            sb.Append(EmitInlineJsonPath(method, messageParams));
            sb.AppendLine();
        }

        // DispatchInfo construction
        sb.Append(EmitDispatchInfoConstruction(method, "Logsmith", hasJsonPath, method.HasExplicitSink));
        sb.AppendLine();

        // Dispatch
        if (method.HasExplicitSink)
        {
            var sinkParam = method.Parameters.First(p => p.Kind == ParameterKind.Sink);
            sb.AppendLine($"        {sinkParam.Name}.Write(in __info);");
        }
        else
        {
            sb.AppendLine("        __ctx.Dispatch(in __info);");
        }

        // Return any ArrayPool buffer rented during overflow
        sb.AppendLine("        writer.Dispose();");
        sb.AppendLine("    }");
        return sb.ToString();
    }

    private static string EmitAbstractionMethodBody(LogMethodInfo method)
    {
        var sb = new StringBuilder();
        string levelName = method.Level >= 0 && method.Level < LogLevelNames.Length
            ? LogLevelNames[method.Level]
            : "Information";
        string absNs = method.AbstractionNamespace;

        // Conditional attribute
        int threshold = ConditionalCompilation.ParseThreshold(method.ConditionalLevel);
        bool applyConditional = ConditionalCompilation.ShouldApplyConditional(
            method.Level, threshold, method.AlwaysEmit);

        if (applyConditional)
        {
            sb.AppendLine("    [global::System.Diagnostics.Conditional(\"DEBUG\")]");
        }

        // Method signature
        sb.Append($"    {method.AccessModifier}static partial void {method.MethodName}(");
        sb.Append(string.Join(", ", method.Parameters.Select(p => FormatParameterAbstraction(p, absNs))));
        sb.AppendLine(")");
        sb.AppendLine("    {");

        bool hasExplicitLogger = HasAbstractionLogger(method);

        // Logger acquisition + IsEnabled guard
        if (hasExplicitLogger)
        {
            var loggerParam = method.Parameters.First(p => p.Kind == ParameterKind.AbstractionLogger);
            sb.AppendLine($"        if (!{loggerParam.Name}.IsEnabled(global::{absNs}.LogLevel.{levelName}, \"{EscapeString(method.Category)}\"))");
            sb.AppendLine("            return;");
            sb.AppendLine($"        var __logger = {loggerParam.Name};");
        }
        else
        {
            sb.AppendLine($"        var __logger = global::{absNs}.LogsmithOutput.Logger;");
            sb.AppendLine($"        if (__logger is null || !__logger.IsEnabled(global::{absNs}.LogLevel.{levelName}, \"{EscapeString(method.Category)}\"))");
            sb.AppendLine("            return;");
        }

        // Sampling guard
        if (method.SampleRate > 1)
        {
            sb.AppendLine();
            sb.Append(EmitSamplingGuard(method));
        }

        // Rate-limiting guard
        if (method.MaxPerSecond > 0)
        {
            sb.AppendLine();
            sb.Append(EmitRateLimitGuard(method));
        }

        sb.AppendLine();

        // Text path
        int bufferSize = EstimateBufferSize(method);
        sb.AppendLine($"        global::System.Span<byte> __buffer = stackalloc byte[{bufferSize}];");
        sb.AppendLine($"        var writer = new global::{absNs}.Utf8LogWriter(__buffer);");
        sb.Append(TextPathEmitter.Emit(method));
        sb.AppendLine("        var __utf8Message = writer.GetWritten();");
        sb.AppendLine();

        // DispatchInfo construction (abstraction mode always fills all fields)
        sb.Append(EmitDispatchInfoConstruction(method, absNs, hasJsonPath: false, isExplicitSink: false));
        sb.AppendLine();

        // Dispatch
        sb.AppendLine("        __logger.Write(in __info);");

        // Return any ArrayPool buffer rented during overflow
        sb.AppendLine("        writer.Dispose();");
        sb.AppendLine("    }");
        return sb.ToString();
    }

    internal static string EmitDispatchInfoConstruction(LogMethodInfo method, string ns,
        bool hasJsonPath = false, bool isExplicitSink = false)
    {
        var sb = new StringBuilder();
        string levelName = method.Level >= 0 && method.Level < LogLevelNames.Length
            ? LogLevelNames[method.Level]
            : "Information";

        // Find special parameters
        string exceptionExpr = "null";
        string callerFileExpr = "null";
        string callerLineExpr = "0";
        string callerMemberExpr = "null";

        foreach (var param in method.Parameters)
        {
            switch (param.Kind)
            {
                case ParameterKind.Exception:
                    exceptionExpr = param.Name;
                    break;
                case ParameterKind.CallerFile:
                    callerFileExpr = param.Name;
                    break;
                case ParameterKind.CallerLine:
                    callerLineExpr = param.Name;
                    break;
                case ParameterKind.CallerMember:
                    callerMemberExpr = param.Name;
                    break;
            }
        }

        sb.AppendLine($"        var __info = new global::{ns}.DispatchInfo");
        sb.AppendLine("        {");
        sb.AppendLine($"            Level = global::{ns}.LogLevel.{levelName},");
        sb.AppendLine($"            EventId = {method.EventId},");

        // When dispatching through LoggerContext, it fills in TimestampTicks, Category, ThreadId, ThreadName.
        // When dispatching through explicit sink, we must fill them ourselves.
        if (isExplicitSink || ns != "Logsmith")
        {
            sb.AppendLine("            TimestampTicks = global::System.DateTime.UtcNow.Ticks,");
            sb.AppendLine($"            Category = \"{EscapeString(method.Category)}\",");
        }

        sb.AppendLine("            Utf8Message = __utf8Message,");

        if (hasJsonPath)
        {
            sb.AppendLine("            Utf8Json = __utf8Json,");
        }

        sb.AppendLine($"            Exception = {exceptionExpr},");
        sb.AppendLine($"            CallerFile = {callerFileExpr},");
        sb.AppendLine($"            CallerLine = {callerLineExpr},");
        sb.AppendLine($"            CallerMember = {callerMemberExpr},");

        if (isExplicitSink || ns != "Logsmith")
        {
            sb.AppendLine("            ThreadId = global::System.Environment.CurrentManagedThreadId,");
            sb.AppendLine("            ThreadName = global::System.Threading.Thread.CurrentThread.Name,");
        }

        sb.AppendLine("        };");

        return sb.ToString();
    }

    private static string EmitInlineJsonPath(LogMethodInfo method, List<ParameterInfo> messageParams)
    {
        var sb = new StringBuilder();

        // Build format specifier lookup
        var formatSpecifiers = new Dictionary<string, string>();
        foreach (var part in method.TemplateParts)
        {
            if (part.IsPlaceholder && part.BoundParameter != null && part.FormatSpecifier != null)
                formatSpecifiers[part.BoundParameter.Name] = part.FormatSpecifier;
        }

        int estimatedSize = messageParams.Count * 64 + 16;
        sb.AppendLine($"        var __jsonBuffer = new global::System.Buffers.ArrayBufferWriter<byte>({estimatedSize});");
        sb.AppendLine("        var __jsonWriter = new global::System.Text.Json.Utf8JsonWriter(__jsonBuffer);");
        sb.AppendLine("        __jsonWriter.WriteStartObject();");

        foreach (var param in messageParams)
        {
            formatSpecifiers.TryGetValue(param.Name, out var formatSpec);
            sb.Append(EmitInlineJsonPropertyWrite(param, formatSpec));
        }

        sb.AppendLine("        __jsonWriter.WriteEndObject();");
        sb.AppendLine("        __jsonWriter.Flush();");
        sb.AppendLine("        var __utf8Json = (global::System.ReadOnlySpan<byte>)__jsonBuffer.WrittenSpan;");

        return sb.ToString();
    }

    private static string EmitInlineJsonPropertyWrite(ParameterInfo param, string formatSpec)
    {
        var sb = new StringBuilder();
        string accessor = param.Name;

        if (param.IsNullableValueType)
        {
            sb.AppendLine($"        if ({accessor}.HasValue)");
            sb.AppendLine($"            {GetInlineJsonWrite(param.Name, accessor + ".Value", param, formatSpec)}");
            sb.AppendLine("        else");
            sb.AppendLine($"            __jsonWriter.WriteNull(\"{param.Name}\");");
        }
        else if (param.IsNullableReferenceType)
        {
            sb.AppendLine($"        if ({accessor} is not null)");
            sb.AppendLine($"            {GetInlineJsonWrite(param.Name, accessor, param, formatSpec)}");
            sb.AppendLine("        else");
            sb.AppendLine($"            __jsonWriter.WriteNull(\"{param.Name}\");");
        }
        else
        {
            sb.AppendLine($"        {GetInlineJsonWrite(param.Name, accessor, param, formatSpec)}");
        }

        return sb.ToString();
    }

    private static string GetInlineJsonWrite(string propertyName, string accessor, ParameterInfo param, string formatSpec)
    {
        if (formatSpec == "json")
        {
            return $"{{ __jsonWriter.WritePropertyName(\"{propertyName}\"); global::System.Text.Json.JsonSerializer.Serialize(__jsonWriter, {accessor}); }}";
        }

        var typeName = param.TypeFullName;

        // Primitive types — write directly without ToString()
        if (typeName == "int" || typeName == "global::System.Int32")
            return $"__jsonWriter.WriteNumber(\"{propertyName}\", {accessor});";
        if (typeName == "long" || typeName == "global::System.Int64")
            return $"__jsonWriter.WriteNumber(\"{propertyName}\", {accessor});";
        if (typeName == "double" || typeName == "global::System.Double")
            return $"__jsonWriter.WriteNumber(\"{propertyName}\", {accessor});";
        if (typeName == "float" || typeName == "global::System.Single")
            return $"__jsonWriter.WriteNumber(\"{propertyName}\", {accessor});";
        if (typeName == "decimal" || typeName == "global::System.Decimal")
            return $"__jsonWriter.WriteNumber(\"{propertyName}\", {accessor});";
        if (typeName == "bool" || typeName == "global::System.Boolean")
            return $"__jsonWriter.WriteBoolean(\"{propertyName}\", {accessor});";
        if (typeName == "global::System.String" || typeName == "string")
            return $"__jsonWriter.WriteString(\"{propertyName}\", {accessor});";
        if (typeName == "global::System.DateTime")
            return $"__jsonWriter.WriteString(\"{propertyName}\", {accessor});";
        if (typeName == "global::System.DateTimeOffset")
            return $"__jsonWriter.WriteString(\"{propertyName}\", {accessor});";
        if (typeName == "global::System.Guid")
            return $"__jsonWriter.WriteString(\"{propertyName}\", {accessor});";

        // Format specifier — use ToString(format) then write as string
        if (formatSpec != null)
            return $"__jsonWriter.WriteString(\"{propertyName}\", {accessor}.ToString(\"{formatSpec}\"));";

        // Fallback — ToString()
        return $"__jsonWriter.WriteString(\"{propertyName}\", {accessor}.ToString());";
    }

    internal static int EstimateBufferSize(LogMethodInfo method)
    {
        int size = 0;

        foreach (var part in method.TemplateParts)
        {
            if (!part.IsPlaceholder)
            {
                // Literal: UTF-8 byte count (approximate as chars for ASCII)
                size += part.Text.Length;
            }
            else if (part.BoundParameter != null)
            {
                var param = part.BoundParameter;
                if (part.FormatSpecifier == "json")
                    size += 256;
                else if (param.TypeFullName == "global::System.String" || param.TypeFullName == "string")
                    size += 128;
                else
                    size += 32;
            }
        }

        // Minimum and maximum bounds
        if (size < 128) size = 128;
        if (size > 4096) size = 4096;

        return size;
    }

    private static string FormatParameter(ParameterInfo param)
    {
        string type = FormatType(param);

        // Caller info: attributes are on the user's definition part already.
        // Don't emit default values on the implementation — they have no effect
        // on partial method implementations and produce CS1066.
        if (param.Kind is ParameterKind.CallerFile or ParameterKind.CallerLine or ParameterKind.CallerMember)
            return $"{type} {param.Name}";

        if (param.HasDefaultValue)
        {
            string defaultStr = param.DefaultValue == null ? "default" : param.DefaultValue.ToString();
            return $"{param.RefKind}{type} {param.Name} = {defaultStr}";
        }

        return $"{param.RefKind}{type} {param.Name}";
    }

    private static string FormatParameterAbstraction(ParameterInfo param, string absNs)
    {
        if (param.Kind == ParameterKind.AbstractionLogger)
            return $"global::{absNs}.ILogsmithLogger {param.Name}";

        return FormatParameter(param);
    }

    private static string FormatType(ParameterInfo param)
    {
        string type = param.TypeFullName;
        if (param.IsNullableValueType)
            type = $"{type}?";
        else if (param.IsNullableReferenceType)
            type = $"{type}?";
        return type;
    }

    internal static string EmitSamplingGuard(LogMethodInfo method)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"        if ((global::System.Threading.Interlocked.Increment(ref __sampleCounter_{method.MethodName}) % {method.SampleRate}) != 0)");
        sb.AppendLine("            return;");
        return sb.ToString();
    }

    internal static string EmitRateLimitGuard(LogMethodInfo method)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"        long __nowSeconds_{method.MethodName} = global::System.DateTime.UtcNow.Ticks / global::System.TimeSpan.TicksPerSecond;");
        sb.AppendLine($"        long __window_{method.MethodName} = global::System.Threading.Volatile.Read(ref __rateWindow_{method.MethodName});");
        sb.AppendLine($"        if (__nowSeconds_{method.MethodName} != __window_{method.MethodName})");
        sb.AppendLine("        {");
        sb.AppendLine($"            global::System.Threading.Interlocked.Exchange(ref __rateWindow_{method.MethodName}, __nowSeconds_{method.MethodName});");
        sb.AppendLine($"            global::System.Threading.Interlocked.Exchange(ref __rateCount_{method.MethodName}, 0);");
        sb.AppendLine("        }");
        sb.AppendLine($"        if (global::System.Threading.Interlocked.Increment(ref __rateCount_{method.MethodName}) > {method.MaxPerSecond})");
        sb.AppendLine("            return;");
        return sb.ToString();
    }

    internal static string EmitStaticCounterFields(LogMethodInfo method)
    {
        var sb = new StringBuilder();

        if (method.SampleRate > 1)
        {
            sb.AppendLine($"    private static int __sampleCounter_{method.MethodName};");
        }

        if (method.MaxPerSecond > 0)
        {
            sb.AppendLine($"    private static long __rateWindow_{method.MethodName};");
            sb.AppendLine($"    private static int __rateCount_{method.MethodName};");
        }

        return sb.ToString();
    }

    private static bool HasAbstractionLogger(LogMethodInfo method)
    {
        return method.Parameters.Any(p => p.Kind == ParameterKind.AbstractionLogger);
    }

    private static string EscapeString(string text)
    {
        return text
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r");
    }
}
