using Microsoft.CodeAnalysis;

namespace Logsmith.Generator.Tests;

[TestFixture]
public class CodeEmissionTests
{
    [Test]
    public void TextPath_UsesUtf8LogWriter()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello {name}")]
                static partial void Greet(string name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("Utf8LogWriter"));
        Assert.That(generated, Does.Contain("WriteString"));
    }

    [Test]
    public void TextPath_FormattingPriorityChain()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Count={count}")]
                static partial void LogCount(int count);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("WriteFormatted"));
    }

    [Test]
    public void ExplicitSink_RoutesToSinkDirectly()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello {name}")]
                static partial void Greet(ILogSink sink, string name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("sink.IsEnabled"));
        Assert.That(generated, Does.Contain("sink.Write"));
        Assert.That(generated, Does.Not.Contain("LogManager.Dispatch"));
    }

    [Test]
    public void DefaultDispatch_CallsLogManager()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello {name}")]
                static partial void Greet(string name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("LogManager.IsEnabled"));
        Assert.That(generated, Does.Contain("LogManager.Dispatch"));
    }

    [Test]
    public void CallerInfo_PassedToLogEntry()
    {
        var source = """
            using Logsmith;
            using System.Runtime.CompilerServices;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet(
                    [CallerFilePath] string file = "",
                    [CallerLineNumber] int line = 0,
                    [CallerMemberName] string member = "");
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("callerFile: file"));
        Assert.That(generated, Does.Contain("callerLine: line"));
        Assert.That(generated, Does.Contain("callerMember: member"));
    }

    [Test]
    public void EventId_AutoGenerated_StableHash()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result1 = GeneratorTestHelper.RunGenerator(compilation);
        var result2 = GeneratorTestHelper.RunGenerator(compilation);

        var gen1 = GetGeneratedSource(result1, "TestNs.Log");
        var gen2 = GetGeneratedSource(result2, "TestNs.Log");
        Assert.That(gen1, Is.EqualTo(gen2));
        Assert.That(gen1, Does.Contain("eventId:"));
    }

    [Test]
    public void EventId_UserOverride_UsesProvidedValue()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello", EventId = 42)]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("eventId: 42"));
    }

    [Test]
    public void NullableValueType_EmitsHasValueGuard()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Value={val}")]
                static partial void LogValue(int? val);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("HasValue"));
    }

    [Test]
    public void NullableRefType_EmitsIsNotNullGuard()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Name={name}")]
                static partial void LogName(string? name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("is not null"));
    }

    [Test]
    public void FormatSpecifier_EmitsWriteFormattedWithFormat()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Count={count:N0}")]
                static partial void LogCount(int count);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("WriteFormatted(count, \"N0\")"));
    }

    [Test]
    public void JsonSpecifier_EmitsSerializeToUtf8Bytes()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Data={data:json}")]
                static partial void LogData(object data);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("SerializeToUtf8Bytes"));
    }

    [Test]
    public void JsonSpecifier_StructuredPath_EmitsSerialize()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Data={data:json}")]
                static partial void LogData(object data);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("JsonSerializer.Serialize(writer"));
    }

    [Test]
    public void ThreadInfo_EmittedInLogEntry()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("threadId: global::System.Environment.CurrentManagedThreadId"));
        Assert.That(generated, Does.Contain("threadName: global::System.Threading.Thread.CurrentThread.Name"));
    }

    [Test]
    public void CategoryName_Constant_EmittedWithClassName()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("public const string CategoryName = \"Log\";"));
    }

    [Test]
    public void CategoryName_Constant_EmittedWithLogCategoryAttribute()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            [LogCategory("MyApp")]
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("public const string CategoryName = \"MyApp\";"));
    }

    [Test]
    public void IsEnabled_PassesCategoryToLogManager()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            [LogCategory("HTTP")]
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Request")]
                static partial void Request();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("LogManager.IsEnabled(global::Logsmith.LogLevel.Information, \"HTTP\")"));
    }

    [Test]
    public void BoolParam_EmitsUtf8Literal_NotWriteFormatted()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Active={active}")]
                static partial void LogActive(bool active);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("\"true\"u8"));
        Assert.That(generated, Does.Contain("\"false\"u8"));
        Assert.That(generated, Does.Not.Contain("WriteFormatted(active"));
    }

    [Test]
    public void NullableBoolParam_EmitsUtf8Literal_WithHasValueGuard()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Active={active}")]
                static partial void LogActive(bool? active);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("HasValue"));
        Assert.That(generated, Does.Contain("\"true\"u8"));
        Assert.That(generated, Does.Contain("\"false\"u8"));
    }

    [Test]
    public void EnumParam_EmitsToString_NotWriteFormatted()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public enum Status { Active, Inactive }
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Status={status}")]
                static partial void LogStatus(Status status);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("ToString()"));
        Assert.That(generated, Does.Not.Contain("WriteFormatted(status"));
    }

    [Test]
    public void CustomStruct_EmitsToString_NotWriteFormatted()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public struct Point { public int X; public int Y; public override string ToString() => $"({X},{Y})"; }
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Pos={pos}")]
                static partial void LogPos(Point pos);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("WriteString(pos.ToString())"));
        Assert.That(generated, Does.Not.Contain("WriteFormatted(pos"));
    }

    [Test]
    public void NonFormattableTypes_GeneratedCode_CompilesCleanly()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public enum Color { Red, Green, Blue }
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Flag={flag} Color={color}")]
                static partial void LogMixed(bool flag, Color color);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var (result, diagnostics) = GeneratorTestHelper.RunGeneratorWithDiagnostics(compilation);

        var errors = diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error).ToList();
        Assert.That(errors, Is.Empty, $"Generated code has compilation errors: {string.Join("\n", errors)}");
    }

    [Test]
    public void IntParam_StillUsesWriteFormatted()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Count={count}")]
                static partial void LogCount(int count);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("WriteFormatted(count)"));
    }

    private static string GetGeneratedSource(GeneratorRunResult result, string hintPrefix)
    {
        var source = result.GeneratedSources
            .FirstOrDefault(s => s.HintName.StartsWith(hintPrefix));
        Assert.That(source.SourceText, Is.Not.Null, $"No generated source found with prefix '{hintPrefix}'");
        return source.SourceText!.ToString();
    }
}
