using Microsoft.CodeAnalysis;

namespace Logsmith.Generator.Tests;

[TestFixture]
public class CodeEmissionTests
{
    [Test]
    public void TextPath_UsesUtf8LogWriter()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello {name}")]
                static partial void Greet(string name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("Utf8LogWriter"));
        Assert.That(generated, Does.Contain("WriteString"));
    }

    [Test]
    public void TextPath_FormattingPriorityChain()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Count={count}")]
                static partial void LogCount(int count);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("WriteFormatted"));
    }

    [Test]
    public void ExplicitSink_RoutesToSinkDirectly()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello {name}")]
                static partial void Greet(ILogSink sink, string name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("sink.IsEnabled"));
        Assert.That(generated, Does.Contain("sink.Write"));
        Assert.That(generated, Does.Not.Contain("LogManager.Dispatch"));
    }

    [Test]
    public void DefaultDispatch_CallsLogManager()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello {name}")]
                static partial void Greet(string name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("LogManager.IsEnabled"));
        Assert.That(generated, Does.Contain("LogManager.Dispatch"));
    }

    [Test]
    public void CallerInfo_PassedToLogEntry()
    {
        var source = """
            using Logsmith;
            using System.Runtime.CompilerServices;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet(
                    [CallerFilePath] string file = "",
                    [CallerLineNumber] int line = 0,
                    [CallerMemberName] string member = "");
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("callerFile: file"));
        Assert.That(generated, Does.Contain("callerLine: line"));
        Assert.That(generated, Does.Contain("callerMember: member"));
    }

    [Test]
    public void EventId_AutoGenerated_StableHash()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result1 = GeneratorTestHelper.RunGenerator(compilation);
        var result2 = GeneratorTestHelper.RunGenerator(compilation);

        var gen1 = GetGeneratedSource(result1, "TestNs.Log");
        var gen2 = GetGeneratedSource(result2, "TestNs.Log");
        Assert.That(gen1, Is.EqualTo(gen2));
        Assert.That(gen1, Does.Contain("eventId:"));
    }

    [Test]
    public void EventId_UserOverride_UsesProvidedValue()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello", EventId = 42)]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("eventId: 42"));
    }

    [Test]
    public void NullableValueType_EmitsHasValueGuard()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Value={val}")]
                static partial void LogValue(int? val);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("HasValue"));
    }

    [Test]
    public void NullableRefType_EmitsIsNotNullGuard()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Name={name}")]
                static partial void LogName(string? name);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("is not null"));
    }

    [Test]
    public void FormatSpecifier_EmitsWriteFormattedWithFormat()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Count={count:N0}")]
                static partial void LogCount(int count);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("WriteFormatted(count, \"N0\")"));
    }

    [Test]
    public void JsonSpecifier_EmitsSerializeToUtf8Bytes()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Data={data:json}")]
                static partial void LogData(object data);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("SerializeToUtf8Bytes"));
    }

    [Test]
    public void JsonSpecifier_StructuredPath_EmitsSerialize()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Data={data:json}")]
                static partial void LogData(object data);
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("JsonSerializer.Serialize(writer"));
    }

    [Test]
    public void ThreadInfo_EmittedInLogEntry()
    {
        var source = """
            using Logsmith;
            namespace TestNs;
            public static partial class Log
            {
                [LogMessage(LogLevel.Information, "Hello")]
                static partial void Greet();
            }
            """;

        var compilation = GeneratorTestHelper.CreateCompilation(source);
        var result = GeneratorTestHelper.RunGenerator(compilation);

        var generated = GetGeneratedSource(result, "TestNs.Log");
        Assert.That(generated, Does.Contain("threadId: global::System.Environment.CurrentManagedThreadId"));
        Assert.That(generated, Does.Contain("threadName: global::System.Threading.Thread.CurrentThread.Name"));
    }

    private static string GetGeneratedSource(GeneratorRunResult result, string hintPrefix)
    {
        var source = result.GeneratedSources
            .FirstOrDefault(s => s.HintName.StartsWith(hintPrefix));
        Assert.That(source.SourceText, Is.Not.Null, $"No generated source found with prefix '{hintPrefix}'");
        return source.SourceText!.ToString();
    }
}
